AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ServerlessAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: serverless/api
      Timeout: 10000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY